// File generated by the FlutterFire CLI — DO NOT hand-edit these values.
//
// This file is a PLACEHOLDER. Before running the app, replace it with your
// own project's config by running, from the project root:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// That command talks to your Firebase project and overwrites this file with
// real apiKey/appId/projectId values for Android, iOS, and web. Committing
// a placeholder (rather than leaving the file out entirely) keeps the
// import in main.dart resolvable so the project still analyzes/compiles
// before you've connected your own Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `flutterfire configure` to generate them.',
        );
    }
  }

  static const web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    projectId: 'launchpad-alu',
    storageBucket: 'launchpad-alu.appspot.com',
  );

  static const android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    projectId: 'launchpad-alu',
    storageBucket: 'launchpad-alu.appspot.com',
  );

  static const ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    projectId: 'launchpad-alu',
    storageBucket: 'launchpad-alu.appspot.com',
    iosBundleId: 'com.example.launchpadAlu',
  );
}
